apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: aleph
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Values.certs.email }}
    privateKeySecretRef:
      name: letsencrypt-staging
    http01: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: aleph
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.certs.email }}
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-{{ .Values.certs.domain }}
  namespace: aleph
spec:
  secretName: tls-{{ .Values.certs.domain }}
  dnsNames:
    - {{ .Values.certs.domain }}
  acme:
    config:
      - http01:
          ingress: ingress-nginx
        domains:
          - {{ .Values.certs.domain }}
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
---