kind: ConfigMap
apiVersion: v1
metadata:
  name: aleph-config
  namespace: {{ .Values.global.namespace }}
data:
  C_FORCE_ROOT: 'true'
  GRPC_VERBOSITY: 'ERROR'
  ALEPH_DEBUG: 'false'
  ALEPH_CACHE: 'true'
  ALEPH_EAGER: 'false'
  ALEPH_URL_SCHEME: {{ .Values.config.ALEPH_URL_SCHEME }}
  ALEPH_APP_TITLE: {{ .Values.config.ALEPH_APP_TITLE }}
  ALEPH_APP_NAME: aleph
  ALEPH_OCR_VISION_API: 'false'
  ALEPH_CORS_ORIGINS: '*'
  ALEPH_ARCHIVE_TYPE: {{ .Values.config.ALEPH_ARCHIVE_TYPE }}
  ALEPH_ARCHIVE_BUCKET: {{ .Values.config.ALEPH_ARCHIVE_BUCKET }}
  ALEPH_PASSWORD_LOGIN: 'true'
  ALEPH_ADMINS: {{ .Values.config.ALEPH_ADMINS }}
  ALEPH_MAIL_FROM: {{ .Values.config.ALEPH_MAIL_FROM }}
  ALEPH_MAIL_HOST: {{ .Values.config.ALEPH_MAIL_HOST }}
  ALEPH_MAIL_USERNAME: {{ .Values.config.ALEPH_MAIL_USERNAME }}
  ALEPH_MAIL_PASSWORD: {{ .Values.config.ALEPH_MAIL_PASSWORD }}
  ALEPH_MAIL_PORT: '25'
  ALEPH_MAIL_TLS: 'false'
  ALEPH_MAIL_SSL: 'false'
  ALEPH_UI_URL: {{ .Values.config.ALEPH_UI_URL }}
  ALEPH_FAVICON: {{ .Values.config.ALEPH_FAVICON }}
  ALEPH_LOGO: {{ .Values.config.ALEPH_LOGO }}
  ALEPH_ELASTICSEARCH_URI: {{ printf "http://es-index.%s.svc.cluster.local:9200/" .Values.global.namespace }}
  ALEPH_ELASTICSEARCH_SHARDS: '20'
  ALEPH_ENTITIES_INDEX: aleph-entity-v2
  ALEPH_ENTITIES_INDEX_SET: aleph-entity-v1
  ALEPH_ENTITIES_INDEX_SPLIT: 'true'
  ALEPH_RECORDS_INDEX: aleph-record-v1
  ALEPH_COLLECTIONS_INDEX: aleph-collection-v2
  ALEPH_BROKER_URI: {{ printf "amqp://guest:guest@task-queue.%s.cluster.local:5672" .Values.global.namespace }}
  ALEPH_REDIS_URL: {{ printf "redis://redis.%s.cluster.local:6379/0" .Values.global.namespace }}
  ALEPH_NER_SERVICE: {{ printf "extract-entities.%s.cluster.local:50000" .Values.global.namespace }}
  ALEPH_OCR_SERVICE: {{ printf "recognize-text.%s.cluster.local:50000" .Values.global.namespace }}
  UNOSERVICE_URL: {{ printf "http://convert-document.%s.cluster.local:3000/convert" .Values.global.namespace }}
  ALEPH_OAUTH: 'false'
  ALEPH_OAUTH_KEY: {{ .Values.config.ALEPH_OAUTH_KEY }}
  ALEPH_OAUTH_NAME: {{ .Values.config.ALEPH_OAUTH_NAME }}
  ALEPH_OAUTH_SCOPE: {{ .Values.config.ALEPH_OAUTH_SCOPE }}
  ALEPH_OAUTH_BASE_URL: {{ .Values.config.ALEPH_OAUTH_BASE_URL }}
  ALEPH_OAUTH_AUTHORIZE_URL: {{ .Values.config.ALEPH_OAUTH_AUTHORIZE_URL }}
  ALEPH_OAUTH_TOKEN_URL: {{ .Values.config.ALEPH_OAUTH_TOKEN_URL }}
  ALEPH_STACKDRIVER_TRACE_PROJECT_ID: {{ .Values.config.ALEPH_STACKDRIVER_TRACE_PROJECT_ID }}
  ALEPH_TRACE_SAMPLING_RATE: {{ .Values.config.ALEPH_TRACE_SAMPLING_RATE | quote }}
  ALEPH_CELERY_TRACE_SAMPLING_RATE: {{ .Values.config.ALEPH_CELERY_TRACE_SAMPLING_RATE | quote }}
