# https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/master/Kubernetes.md
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
  - port: 5432
    targetPort: port-db
  selector:
    app: db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: {{ .Values.global.namespace }}
  annotations:
    date/deploy-date: {{ now | quote }}
spec:
  replicas: {{ .Values.db.replicas }}
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - image: b.gcr.io/cloudsql-docker/gce-proxy:latest
          imagePullPolicy: Always
          name: db
          command:
            - /cloud_sql_proxy
            - -dir=/cloudsql
            - -instances={{ printf "%s=tcp:0.0.0.0:5432" .Values.global.dbInstance }}
            - -credential_file=/credentials/service-account.json
          ports:
            - name: port-db
              containerPort: 5432
          volumeMounts:
            - mountPath: /credentials
              name: service-account-db
          resources:
            requests:
              cpu: "0.1"
              memory: 100Mi
            limits:
              cpu: "0.1"
              memory: 100Mi
          livenessProbe:
            exec:
              command: ["nc", "-z", "127.0.0.1", "5432"]
          readinessProbe:
            exec:
              command: ["nc", "-z", "127.0.0.1", "5432"]
      volumes:
        - name: service-account-db
          secret:
            secretName: service-account-db