apiVersion: v1
kind: Service
metadata:
  name: es-index
  namespace: aleph
  labels:
    app: es-index
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  # clusterIP: None
  publishNotReadyAddresses: true
  sessionAffinity: None
  ports:
    - port: 9200
      targetPort: 9200
      name: serving
    - port: 9300
      targetPort: 9300
      name: node-to-node
  selector:
    app: es-index
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-index
  namespace: aleph
  labels:
    app: es-index
spec:
  serviceName: es-index
  replicas: {{ .Values.index.replicas }}
  selector:
    matchLabels:
      app: es-index
  template:
    metadata:
      labels:
        app: es-index
    spec:
      affinity: # Ask k8s to preferr that pods are placed across zones if available
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ .Values.global.reponame }}
              topologyKey: failure-domain.beta.kubernetes.io/zone
      terminationGracePeriodSeconds: 300
      initContainers:
        # NOTE:
        # This is to fix the permission on the volume
        # By default elasticsearch container is not run as
        # non root user.
        # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_notes_for_production_use_and_defaults
        - name: fix-the-volume-permission
          image: busybox
          command:
            - sh
            - -c
            - chown -R 1000:1000 /usr/share/elasticsearch/data
          securityContext:
            privileged: true
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
        # NOTE:
        # To increase the default vm.max_map_count to 262144
        # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode
        - name: increase-the-vm-max-map-count
          image: busybox
          command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          securityContext:
            privileged: true
        # To increase the ulimit
        # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_notes_for_production_use_and_defaults
        - name: increase-the-fd-ulimit
          image: busybox
          command:
            - sh
            - -c
            - ulimit -n 65536
          securityContext:
            privileged: true
        # - name: increase-the-mlockall-ulimit
        #   image: busybox
        #   command:
        #     - sh
        #     - -c
        #     - ulimit -l unlimited
        #   securityContext:
        #     privileged: true
      containers:
        - name: elasticsearch
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
                - SYS_RESOURCE
          image: alephdata/aleph-elasticsearch:6
          command:
            - /k8s-entrypoint.sh
            - eswrapper
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: tcp
          # NOTE: you can increase this resources
          resources:
            requests:
              memory: {{ .Values.index.resources.requests.memory }}
              cpu: {{ .Values.index.resources.requests.cpu }}
            limits:
              memory: {{ .Values.index.resources.limits.memory }}
              cpu: {{ .Values.index.resources.limits.cpu }}
          env:
            - name: cluster.name
              value: es-index
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: discovery.zen.ping.unicast.hosts
              value: es-index.aleph.svc.cluster.local
            - name: discovery.zen.minimum_master_nodes
              value: {{ .Values.index.minMasterNodes | quote }}
            - name: bootstrap.memory_lock
              value: "true"
            - name: ES_JAVA_OPTS
              value: -Djava.net.preferIPv4Stack=true {{ .Values.index.ES_JAVA_OPTS_MEMORY_LIMIT }}
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
    - metadata:
        name: data
        namespace: aleph
      spec:
        {{- if (.Values.storage.index) and (.Values.storage.index.pvc) }}
        selector:
          matchLabels:
            service: es-index
        {{- end }}
        accessModes:
          - ReadWriteOnce
        storageClassName: ssd
        resources:
          requests:
            storage: {{ .Values.index.resources.requests.storage }}
