apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - port: 6379
      name: redis
  selector:
    app: redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: {{ .Values.global.namespace }}
  annotations:
    date/deploy-date: {{ now | quote }}
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
              name: redis
          args:
            - --save
            - "1200"
            - "1"
            - --maxmemory
            - {{ .Values.redis.maxMemory }}
            - --maxmemory-policy
            - volatile-ttl
          resources:
            requests:
              memory: {{ .Values.redis.resources.requests.memory }}
              cpu: {{ .Values.redis.resources.requests.cpu }}
            limits:
              memory: {{ .Values.redis.resources.limits.memory }}
              cpu: {{ .Values.redis.resources.limits.cpu }}
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
        namespace: {{ .Values.global.namespace }}
      spec:
        {{- if (.Values.storage.redis) and (.Values.storage.redis.pvc) }}
        selector:
          matchLabels:
            service: redis
        {{- end }}
        accessModes:
          - ReadWriteOnce
        storageClassName: ssd
        resources:
          requests:
            storage: {{ .Values.redis.resources.requests.storage }}