# SPDX-FileCopyrightText: 2022 2014-2015 Friedrich Lindenberg, <friedrich@pudo.org>, et al.
# SPDX-FileCopyrightText: 2022 2016-2020 Journalism Development Network,Inc
#
# SPDX-License-Identifier: MIT

apiVersion: v2
name: aleph
description: Helm chart for Aleph
type: application
version: 3.12.4
appVersion: 3.12.4
