FROM pudo/aleph-base:1.4

# Begin python festivities
COPY requirements.txt /tmp/requirements.txt
RUN pip install --upgrade pip && pip install -q functools32 \
  && pip install -r /tmp/requirements.txt
