FROM pudo/aleph-base:1.4

# Begin python festivities
COPY requirements.txt /tmp/requirements.txt
COPY bower.json /tmp/bower.json
RUN pip install --upgrade pip && pip install functools32 \
    && pip install -r /tmp/requirements.txt \
    && pip install newrelic==2.46.0.37 \
                   gevent==1.0.2 \
                   greenlet==0.4.5
