system:
  - name: 'aleph_system'
    type: 'Info'
    description: 'Aleph version and FollowTheMoney version'
  - name: 'ingestfile_system'
    type: 'Info'
    description: 'ingest-file version'
usage:
  - name: 'aleph_users'
    type: 'Gauge'
    description: 'Number of users'
  - name: 'aleph_collections'
    type: 'Gauge'
    description: 'Number of collections (by category)'
  - name: 'aleph_collection_users'
    type: 'Gauge'
    description: 'Number of users that have created at least one collection (by category)'
  - name: 'aleph_entitysets'
    type: 'Gauge'
    description: 'Number of entity sets (by type)'
  - name: 'aleph_entityset_users'
    type: 'Gauge'
    description: 'Number of users that have created at least one entity set (by type)'
  - name: 'aleph_bookmarks'
    type: 'Gauge'
    description: 'Number of bookmarks'
  - name: 'aleph_bookmark_users'
    type: 'Gauge'
    description: 'Number of users that have created at least one bookmark'
api:
  - name: 'aleph_http_request_duration_seconds'
    type: 'Histogram'
    description: 'Duration of requests to the Aleph API in seconds'
  - name: 'aleph_http_requests_total'
    type: 'Counter'
    description: 'Total number of requests to the Aleph API'
  - name: 'aleph_streamed_entities_total'
    type: 'Counter'
    description: 'Total number of entities returned by the Aleph API streaming endpoint'
  - name: 'aleph_streams_total'
    type: 'Counter'
    description: 'Total number of requests to the Aleph API streaming endpoint'
xref:
  - name: 'aleph_xref_entities_total'
    type: 'Counter'
    description: 'Total number of entities that have been cross-referenced'
  - name: 'aleph_xref_matches'
    type: 'Histogram'
    description: 'Number of matches per cross-referenced entity'
  - name: 'aleph_xref_candidates_query_duration_seconds'
    type: 'Histogram'
    description: 'Processing duration of the Elasticsearch query to fetch cross-referencing candidates for an entity (excluding network, serialization, etc.)'
  - name: 'aleph_xref_candidates_query_roundtrip_duration_seconds'
    type: 'Histogram'
    description: 'Roundtrip duration of the Elasticsearch query to fetch cross-referencing candidates for an entity (including network, serialization, etc.)'
auth:
  - name: 'aleph_auth_attempts'
    type: 'Counter'
    description: 'Number of authentication attempts (by results and authentication method)'
queues:
  - name: 'aleph_active_datasets'
    type: 'Gauge'
    description: 'Number of datasets with active jobs'
  - name: 'aleph_tasks'
    type: 'Gauge'
    description: 'Number of pending and running tasks (by stage)'
workers:
  - name: 'servicelayer_tasks_started_total'
    type: 'Counter'
    description: 'Number of tasks that a worker has started to process (by stage and number of retries)'
  - name: 'servicelayer_tasks_succeeded_total'
    type: 'Counter'
    description: 'Number of tasks that have been successfully processed (by stage and number of retries)'
  - name: 'servicelayer_tasks_failed_total'
    type: 'Counter'
    description: 'Number of tasks that have failed (by stage)'
  - name: 'servicelayer_task_duration_seconds'
    type: 'Counter'
    description: 'Processing duration for successfully processed tasks in seconds (by stage)'
ingestion:
  - name: 'ingestfile_ingestions_succeeded_total'
    type: 'Counter'
    description: 'Number of successful ingestions (by ingestor)'
  - name: 'ingestfile_ingestions_failed_total'
    type: 'Counter'
    description: 'Number of failed ingestions (by ingestor)'
  - name: 'ingestfile_ingestion_duration_seconds'
    type: 'Histogram'
    description: 'Processing duration for successfully processed tasks in seconds (by ingestor)'
  - name: 'ingestfile_pdf_cache_accessed'
    type: 'Counter'
    description: 'Number of times the PDF cache has been accessed (by cache status)'
