# SPDX-FileCopyrightText: 2022 2014-2015 Friedrich Lindenberg, <friedrich@pudo.org>, et al.
# SPDX-FileCopyrightText: 2022 2016-2020 Journalism Development Network,Inc
#
# SPDX-License-Identifier: MIT

kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.global.namingPrefix }}-aleph-config
data:
  {{- toYaml .Values.global.commonEnv | nindent 2}}
  {{- toYaml .Values.global.env | nindent 2}}
