###################################################################
#
# Node types.
#
###################################################################
entities:
  Entity:
    hidden: true
    icon: fa-circle
    properties:
      name:
        label: Name
        type: name
        hidden: true
      summary:
        label: Summary
      description:
        label: Description
      country:
        label: Country
        type: country
      alias:
        label: Other name
        type: name
        multiple: true
      previousName:
        label: Previous name
        type: name
        multiple: true
      weakAlias:
        label: Weak alias
        multiple: true
      sourceUrl:
        label: Source link
        type: url
      icijId:
        label: ICIJ ID
      tags:
        label: Relevancy
      keywords:
        label: Keywords
        multiple: true
      address:
        label: Address
        type: address
      notes:
        label: Notes

  LegalEntity:
    extends: Entity
    label: Legal entity
    plural: Legal entities
    icon: fa-user-secret
    properties:
      email:
        label: E-Mail
        type: email
      phone:
        label: Phone
        type: phone
      website:
        label: Website
        type: url
      legalForm:
        label: Legal form
      incorporationDate:
        label: Incorporation date
        type: date
      dissolutionDate:
        label: Dissolution date
        type: date
      taxStatus:
        label: Tax status
      status:
        label: Status
      sector:
        label: Sector
      program: # Used by sanctions
        label: Program
      classification:
        label: Classification
      registrationNumber:
        label: Registration number
        type: identifier
      idNumber:
        label: ID Number
        type: identifier
      taxNumber:
        label: Tax ID Number
        type: identifier
      bankAccount:
        label: Bank account
      jurisdiction:
        label: Jurisdiction
        type: country
      mainCountry:
        label: Country of origin
        type: country

  Organization:
    extends: LegalEntity
    label: Organization
    plural: Organizations
    icon: fa-university

  Person:
    extends: LegalEntity
    label: Person
    plural: People
    icon: fa-user
    properties:
      title:
        label: Title
      firstName:
        label: First name
      secondName:
        label: Second name
      middleName:
        label: Middle name
      lastName:
        label: Last name
      birthDate:
        label: Birth date
        type: date
      birthPlace:
        label: Place of birth
      deathDate:
        label: Death date
        type: date
      position:
        label: Position
      nationality:
        label: Nationality
        type: country
      gender:
        label: Gender
      passportNumber:
        label: Passport
        type: identifier

  Company:
    label: Company
    plural: Companies
    icon: fa-industry
    extends:
      - Organization
      - Asset
    properties:
      capital:
        label: "Capital"
      voenCode:
        label: "VOEN"
      okpoCode:
        label: "OKPO"
      innCode:
        label: "INN"
      coatoCode:
        label: "COATO"
      vatCode:
        label: "VAT Identifier"
      irsCode:
        label: "IRS Number"
      ipoCode:
        label: "IPO"
      cikCode:
        label: "SEC Central Index Key"
      jibCode:
        label: "JIB"
      mbsCode:
        label: "MBS"

  PublicBody:
    label: Public body
    plural: Public bodies
    icon: fa-building
    extends: Organization
    fuzzy: false

  Asset:
    plural: Assets
    extends: Entity
    icon: fa-car
    hidden: true
    fuzzy: false
    properties:
      value:
        label: Value
      valueCurrency:
        label: Value (Currency)

  Concession:
    label: Concession
    plural: Concessions
    extends: Asset
    icon: fa-th
    fuzzy: false
    properties:
      area:
        label: Area
      commodities:
        label: Commodities

  Land:
    label: Land
    plural: Lands
    extends: Asset
    icon: fa-map
    fuzzy: false
    properties:
      address:
        label: Address
        type: address
      location:
        label: Location
      censusBlock:
        label: Census block
      cadastralCode:
        label: Cadastral code
      area:
        label: Area
      registrationNumber:
        label: Registration number
      propertyType:
        label: Property type
      landType:
        label: Land type
      createDate:
        label: Record date

  CourtCase:
    label: Court case
    plural: Court cases
    extends: Entity
    icon: fa-briefcase
    fuzzy: false
    properties:
      category:
        label: Category
      type:
        label: Type
      status:
        label: Status


###################################################################
#
# Relationship types.
#
###################################################################
links:
  link:
    label: "Link"
    hidden: true
    properties:
      startDate:
        label: "Start date"
        type: date
      endDate:
        label: "End date"
        type: date
      date:
        label: "Date"
        type: date
      summary:
        label: "Summary"
      role:
        label: "Role"
      recordId:
        label: "Record ID"
      sourceUrl:
        label: Source link
        type: url

  controlledBy:
    label: "Control"
    forward: "Controlled by"
    reverse: "Controls"
    extends: link

  ownedBy:
    label: "Ownership"
    forward: "Owned by"
    reverse: "Owns"
    extends: controlledBy
    properties:
      percentage:
        label: "Percentage held"
      value:
        label: "Value of shares"
      shareCount:
        label: "Number of shares"
      shareType:
        label: "Type of shares"
      shareCurrency:
        label: "Currency of shares"
      legalBasis:
        label: "Legal basis"
      status:
        label: "Status"
      ownershipType:
        label: "Type of ownership"

  directedBy:
    label: "Directorship"
    forward: "Directed by"
    reverse: "Directs"
    extends: controlledBy
    properties:
      position:
        label: "Position"
      secretary:
        label: "Secretary"

  managedBy:
    label: "Management"
    forward: "Managed by"
    reverse: "Manages"
    extends: link

  memberOf:
    label: "Membership"
    forward: "Member of"
    reverse: "Has member"
    extends: link

  linkedTo:
    label: "Association"
    forward: "Linked to"
    reverse: "Linked to"
    extends: link

  contractedBy:
    label: "Contract awards"
    forward: "Received contract to"
    reverse: "Awarded contract from"
    extends: link
    properties:
      totalValue:
        label: Total value
      type:
        label: Type
      procedureNumber:
        label: Procedure number
      documentNumber:
        label: Document number
      decisionReason:
        label: Decision basis
      documentDate:
        label: Document date
        type: date
      cpvCode:
        label: CPV code

  paidBy:
    label: "Payment"
    forward: "Paid by"
    reverse: "Paid"
    extends: link
    properties:
      amount:
        label: "Amount"
      currency:
        label: "Currency"
      amountUsd:
        label: "Amount (USD)"
      sequenceNumber:
        label: "Sequence Number"
      transactionNumber:
        label: "Transaction Number"
      purpose:
        label: "Purpose"
      payerAccount:
        label: "Payer account"
      payerBank:
        label: "Payer bank"
      beneficiaryAccount:
        label: "Beneficiary account"
      beneficiaryBank:
        label: "Beneficiary bank"
