blank_issues_enabled: false
contact_links:
  - name: Aleph Community Discourse
    url: https://aleph.discourse.group
    about: Get support for running and developing Aleph and related projects here.
