FROM python:3.6-stretch

# sudo apt-get install curl autoconf automake libtool pkg-config
# git clone https://github.com/openvenues/libpostal
# cd libpostal
# ./bootstrap.sh
# ./configure --datadir=[...some dir with a few GB of space...]
# make -j4
# sudo make install

# # On Linux it's probably a good idea to run
# sudo ldconfig
