apiVersion: v1
kind: Service
metadata:
  name: search-api
  labels:
    app: search-api
spec:
  selector:
    app: search-api
  ports:
    - port: 8000
      targetPort: 8000
      protocol: "TCP"
      name: api
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: search-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: search-api
  minReplicas: {{ .Values.api.minReplicas }}
  maxReplicas: {{ .Values.api.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.api.targetAverageCPUUtilization }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-api
  labels:
    app: search-api
spec:
  selector:
    matchLabels:
      app: search-api
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.api.maxSurge }}
      maxUnavailable: {{ .Values.api.maxUnavailable }}
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: search-api
    spec:
      nodeSelector:
        tier: application
        lifespan: permanent
      restartPolicy: Always
      containers:
        - name: search-api
          image: {{ .Values.api.image }}
          imagePullPolicy: Always
          command:
            - gunicorn 
            - -t
            - '3600'
            - -w
            - '8'
            - -b
            - 0.0.0.0:8000
            - --log-level
            - debug
            - --log-file
            - '-'
            # - --access-logfile
            # - '-'
            - aleph.manage:app
          resources:
            requests:
              memory: {{ .Value.api.resources.requests.memory }}
            limits:
              memory: {{ .Value.api.resources.limits.memory }}
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/service-account.json
            - name: ALEPH_DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: common-secrets
                  key: ALEPH_DATABASE_URI
            - name: ALEPH_OAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: common-secrets
                  key: ALEPH_OAUTH_SECRET
            - name: ALEPH_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: common-secrets
                  key: ALEPH_SECRET_KEY
          envFrom:
            - configMapRef:
                name: search-config
          volumeMounts:
            - mountPath: /var/secrets/google
              name: service-account-app
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 30
        - name: search-db-sidecar
          image: b.gcr.io/cloudsql-docker/gce-proxy:latest
          imagePullPolicy: Always
          command:
            - /cloud_sql_proxy
            - -dir=/cloudsql
            - -instances={{ .Values.global.dbInstance }}
            - -credential_file=/credentials/service-account.json
          volumeMounts:
            - mountPath: /credentials
              name: service-account-db
      volumes:
        - name: service-account-app
          secret:
            secretName: service-account-app
        - name: service-account-db
          secret:
            secretName: service-account-db
