apiVersion: v1
kind: Service
metadata:
  name: search-index-admin
  labels:
    app: search-index-admin
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: search-index-admin
  ports:
    - port: 9000
      targetPort: 9000
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-index-admin
  labels:
    app: search-index-admin
spec:
  replicas: {{ Values.index-admin.replicas }}
  selector:
    matchLabels:
      app: search-index-admin
  strategy:
    rollingUpdate:
      maxSurge: {{ Values.index-admin.maxSurge }}
      maxUnavailable: {{ Values.index-admin.maxUnavailable }}
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: search-index-admin
    spec:
      nodeSelector:
        tier: application
      restartPolicy: Always
      containers:
        - name: index-admin
          image: {{ .Values.index-admin.image }}
          ports:
            - containerPort: 9000
              name: http
          # env:
          #   - name: HQ_DEFAULT_URL
          #     value: http://search-index:9200
          resources:
            limits:
              memory: {{ Values.index-admin.resources.limits.memory }}