"""deleted_at everywhere

Revision ID: 0910f8c739af
Revises: 93aab0a94bed
Create Date: 2016-03-18 21:55:07.707517

"""

# revision identifiers, used by Alembic.
revision = '0910f8c739af'
down_revision = '93aab0a94bed'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('permission', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('role', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('watchlist', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watchlist', 'deleted_at')
    op.drop_column('role', 'deleted_at')
    op.drop_column('permission', 'deleted_at')
    op.drop_column('entity', 'deleted_at')
    ### end Alembic commands ###
