"""use time for alerts

Revision ID: 670af22aca83
Revises: e73ddafacd6d
Create Date: 2016-03-04 12:15:43.980223

"""

# revision identifiers, used by Alembic.
revision = "670af22aca83"
down_revision = "e73ddafacd6d"

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column("alert", sa.Column("notified_at", sa.DateTime(), nullable=True))
    op.drop_column("alert", "max_id")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "alert", sa.Column("max_id", sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.drop_column("alert", "notified_at")
    ### end Alembic commands ###
