"""add updated_at column to audit

Revision ID: a507fabdc439
Revises: a1a4f4eccae5
Create Date: 2018-08-03 06:01:32.287802

"""

# revision identifiers, used by Alembic.
revision = 'a507fabdc439'
down_revision = 'a1a4f4eccae5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit', 'updated_at')
    # ### end Alembic commands ###
