"""empty message

Revision ID: e003034f4af8
Revises: c52a1f469ac7
Create Date: 2025-05-21 17:22:03.575290

"""

# revision identifiers, used by Alembic.
revision = 'e003034f4af8'
down_revision = 'c52a1f469ac7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookmark', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('bookmark', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bookmark', 'collection_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bookmark', 'entity_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_constraint('bookmark_role_id_entity_id_key', 'bookmark', type_='unique')
    op.drop_index('ix_bookmark_role_id_collection_id_created_at', table_name='bookmark')
    op.add_column('collection', sa.Column('contains_ai', sa.Boolean(), nullable=True))
    op.add_column('collection', sa.Column('contains_ai_comment', sa.Unicode(), nullable=True))
    op.alter_column('entityset', 'type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('entityset', 'collection_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('entityset', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('entityset', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entityset', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('entityset', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('entityset', 'collection_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('entityset', 'type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_column('collection', 'contains_ai_comment')
    op.drop_column('collection', 'contains_ai')
    op.create_index('ix_bookmark_role_id_collection_id_created_at', 'bookmark', ['role_id', 'collection_id', 'created_at'], unique=False)
    op.create_unique_constraint('bookmark_role_id_entity_id_key', 'bookmark', ['role_id', 'entity_id'])
    op.alter_column('bookmark', 'entity_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('bookmark', 'collection_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookmark', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookmark', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
