"""Create EntitySet models

Revision ID: e5c7604f6784
Revises: 8dff301e1b1f
Create Date: 2020-06-29 16:18:24.548956

"""

# revision identifiers, used by Alembic.
revision = 'e5c7604f6784'
down_revision = '8dff301e1b1f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entityset',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('label', sa.Unicode(), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.Column('summary', sa.Unicode(), nullable=True),
    sa.Column('layout', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['entityset.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entityset_collection_id'), 'entityset', ['collection_id'], unique=False)
    op.create_index(op.f('ix_entityset_parent_id'), 'entityset', ['parent_id'], unique=False)
    op.create_index(op.f('ix_entityset_role_id'), 'entityset', ['role_id'], unique=False)
    op.create_index(op.f('ix_entityset_type'), 'entityset', ['type'], unique=False)
    op.create_table('entityset_item',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('entityset_id', sa.String(length=128), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['entityset_id'], ['entityset.id'], ),
    sa.PrimaryKeyConstraint('entityset_id', 'entity_id')
    )
    op.create_index(op.f('ix_entityset_item_collection_id'), 'entityset_item', ['collection_id'], unique=False)
    op.create_index(op.f('ix_entityset_item_entity_id'), 'entityset_item', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entityset_item_entityset_id'), 'entityset_item', ['entityset_id'], unique=False)
    op.drop_column('collection', 'casefile')
    op.alter_column('role', 'is_muted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'is_muted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('collection', sa.Column('casefile', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_entityset_item_entityset_id'), table_name='entityset_item')
    op.drop_index(op.f('ix_entityset_item_entity_id'), table_name='entityset_item')
    op.drop_index(op.f('ix_entityset_item_collection_id'), table_name='entityset_item')
    op.drop_table('entityset_item')
    op.drop_index(op.f('ix_entityset_type'), table_name='entityset')
    op.drop_index(op.f('ix_entityset_role_id'), table_name='entityset')
    op.drop_index(op.f('ix_entityset_parent_id'), table_name='entityset')
    op.drop_index(op.f('ix_entityset_collection_id'), table_name='entityset')
    op.drop_table('entityset')
    # ### end Alembic commands ###
