apiVersion: v1
kind: Service
metadata:
  name: search-extract-entities
  namespace: aleph
  labels:
    app: search-extract-entities
spec:
  selector:
    app: search-extract-entities
  ports:
    - port: 50000
      targetPort: 50000
      protocol: "TCP"
      name: grpc-api
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: search-extract-entities
  namespace: aleph
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: search-extract-entities
  minReplicas: REPLACEME:REPLICAS_EXTRACT_ENTITIES_MIN
  maxReplicas: REPLACEME:REPLICAS_EXTRACT_ENTITIES_MAX
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 90
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-extract-entities
  namespace: aleph
  labels:
    app: search-extract-entities
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-extract-entities
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: search-extract-entities
    spec:
      restartPolicy: Always
      containers:
        - name: search-extract-entities
          image: alephdata/aleph-extract-entities:2.2.1
          imagePullPolicy: Always
          ports:
            - containerPort: 50000
              name: grpc-api
          resources:
            requests:
              cpu: REPLACEME:CPU_LIMIT_EXTRACT_ENTITIES
              memory: REPLACEME:MEMORY_LIMIT_EXTRACT_ENTITIES
            limits:
              cpu: REPLACEME:CPU_LIMIT_EXTRACT_ENTITIES
              memory: REPLACEME:MEMORY_LIMIT_EXTRACT_ENTITIES
