apiVersion: v1
kind: Service
metadata:
  name: search-extract-countries
  namespace: aleph
  labels:
    app: search-extract-countries
spec:
  selector:
    app: search-extract-countries
  ports:
    - port: 50000
      targetPort: 50000
      protocol: "TCP"
      name: grpc-api
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: search-extract-countries
  namespace: aleph
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: search-extract-countries
  minReplicas: REPLACEME:REPLICAS_EXTRACT_COUNTRIES_MIN
  maxReplicas: REPLACEME:REPLICAS_EXTRACT_COUNTRIES_MAX
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: search-extract-countries-policy
  namespace: aleph
spec:
  podSelector:
    matchLabels:
      app: search-extract-countries
  policyTypes:
    - Egress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-extract-countries
  namespace: aleph
  labels:
    app: search-extract-countries
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-extract-countries
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: search-extract-countries
    spec:
      affinity: # Ask k8s to preferr that pods are placed across zones if available
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{env "REPONAME"}}
              topologyKey: failure-domain.beta.kubernetes.io/zone
      restartPolicy: Always
      containers:
        - name: search-extract-countries
          image: alephdata/aleph-extract-countries:2.2.1
          imagePullPolicy: Always
          ports:
            - containerPort: 50000
              name: grpc-api
          resources:
            requests:
              cpu: REPLACEME:CPU_LIMIT_EXTRACT_COUNTRIES
              memory: REPLACEME:MEMORY_LIMIT_EXTRACT_COUNTRIES
            limits:
              cpu: REPLACEME:CPU_LIMIT_EXTRACT_COUNTRIES
              memory: REPLACEME:MEMORY_LIMIT_EXTRACT_COUNTRIES
