apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: search-worker
  namespace: aleph
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: search-worker
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-worker
  namespace: aleph
  labels:
    app: search-worker
spec:
  selector:
    matchLabels:
      app: search-worker
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 75%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: search-worker
    spec:
      affinity: # Ask k8s to preferr that pods are placed across zones if available
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{env "REPONAME"}}
              topologyKey: failure-domain.beta.kubernetes.io/zone
      restartPolicy: Always
      containers:
        - name: search-worker
          image: alephdata/aleph:2.2.1
          imagePullPolicy: Always
          command:
            - celery
            - -A
            - aleph.queues
            - -c
            - '4'
            - -l
            - INFO
            - worker
          resources:
            requests:
              memory: REPLACEME:MEMORY_LIMIT_WORKER
              cpu: REPLACEME:CPU_LIMIT_WORKER
            limits:
              memory: REPLACEME:MEMORY_LIMIT_WORKER
              cpu: REPLACEME:CPU_LIMIT_WORKER
#          env:
#            - name: DATAVAULT_DATABASE_URI
#              valueFrom:
#                secretKeyRef:
#                  name: common-secrets
#                  key: DATAVAULT_SIDECAR_URI
          envFrom:
            - configMapRef:
                name: search-config
            - secretRef:
                name: common-secrets
          volumeMounts:
            - mountPath: /secrets
              name: secrets-mounted
        - name: search-db-sidecar
          image: b.gcr.io/cloudsql-docker/gce-proxy:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: 64Mi
              cpu: "0.1"
            limits:
              memory: 64Mi
              cpu: "0.1"
          command:
            - /cloud_sql_proxy
            - -dir=/cloudsql
            - -instances=REPLACEME:SQL_CONNECTION_STRING
            - -credential_file=/secrets/service-account.json
          livenessProbe:
            exec:
              command:
                - nc
                - -z
                - 127.0.0.1
                - "5432"
          readinessProbe:
            exec:
              command:
                - nc
                - -z
                - 127.0.0.1
                - "5432"
          volumeMounts:
            - mountPath: /secrets
              name: secrets-mounted
      volumes:
        - name: secrets-mounted
          secret:
            secretName: secrets-mounted
