SPDX-FileCopyrightText: 2022 2014-2015 Friedrich Lindenberg, <friedrich@pudo.org>, et al.
SPDX-FileCopyrightText: 2022 2016-2020 Journalism Development Network,Inc

SPDX-License-Identifier: MIT

FROM alephdata/aleph-ui:${ALEPH_TAG:-latest} AS builder
RUN npm run build

FROM nginx:alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /alephui/build /assets
