ARG ALEPH_TAG
FROM ghcr.io/openaleph/aleph-ui-base:sha-${ALEPH_TAG} AS builder
LABEL org.opencontainers.image.source = "https://github.com/openaleph/openaleph/ui"

RUN npm run messages
RUN npm run build

FROM nginx:alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /alephui/build /assets
